#!/bin/bash -ex

# when updating, change LTS version here & also update doc link in README
LTS=v6
version=$(gh_releases laravel/laravel | grep -vi "beta\|rc" | grep $LTS | tail -1)
VERSION="${version#v}"

SRC=/usr/local/src
NAME=laravel
WEBROOT=/var/www/laravel

DB_NAME=laravel
DB_USER=laravel
DB_PASS=$(mcookie)

# Download Laravel
mkdir -p $WEBROOT
chown -R www-data:www-data $WEBROOT
turnkey-composer create-project laravel/laravel $WEBROOT $VERSION --prefer-dist --keep-vcs

# Ensure that turnkey-artisan knows where webroot is
sed -i "\|^export WEBROOT| s|=.*|="$WEBROOT"|" /usr/local/bin/turnkey-artisan

# start mysql server
service mysql start

# setup the database
mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop mysql server
service mysql stop

# setup apache configuration
a2dissite 000-default
a2ensite laravel
a2enmod rewrite

# Set Laravel configuration
sed -i '\|^APP_NAME=| s|=.*|="TurnKey Laravel"|' $WEBROOT/.env
sed -i "\|^DB_USERNAME=|=.*|=$DB_USER|" $WEBROOT/.env
sed -i "\|^DB_PASSWORD=| s|=.*|=$DB_PASS|" $WEBROOT/.env

# tweak laravel landing page
WELCOME=$WEBROOT/resources/views/welcome.blade.php
sed -i "\|laravel.com/docs| s|docs|docs/${VERSION%%.*}.x|" $WELCOME
sed -i '\|class="links"|a \                    HERE' $WELCOME
sed -i 's|HERE|<a href="https://www.turnkeylinux.org/laravel">TurnKey</a>|' $WELCOME
