#!/bin/bash -e
# regenerate laravel API secret and mysql user password

. /etc/default/inithooks

WEBROOT=/var/www/laravel
CONF=$WEBROOT/.env

DB_USER=laravel
DB_PASS=$(mcookie)

sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

turnkey-artisan config:cache
turnkey-artisan key:generate --ansi --force
turnkey-artisan config:clear
